'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { api } from '@/lib/api'

const card={background:'#12151e',border:'1px solid #1e2535',borderRadius:10,padding:16}; const mono={fontFamily:'var(--font-mono),ui-monospace,monospace'}
export default function OrgIntelligencePage({params}) {
  const id=params.orgId; const [data,setData]=useState(null); const [error,setError]=useState(''); const [selected,setSelected]=useState(null); const [content,setContent]=useState(''); const [summary,setSummary]=useState(''); const [saving,setSaving]=useState(false); const [complaint,setComplaint]=useState(''); const [override,setOverride]=useState(''); const [model,setModel]=useState('gpt-4o-mini'); const [run,setRun]=useState(null); const [running,setRunning]=useState(false)
  function load(){ return api.getObservabilityOrg(id).then(d=>{setData(d); if(!selected&&d.prompts?.[0]) choose(d.prompts[0],d)}) }
  function choose(p,d=data){setSelected(p.prompt_key); setContent(p.content); setSummary('');}
  useEffect(()=>{load().catch(e=>setError(e.message))},[id])
  async function save(){setSaving(true);try{await api.saveObservabilityPrompt(id,{prompt_key:selected,content,change_summary:summary});await load();setSummary('')}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function rollback(version){setSaving(true);try{await api.rollbackObservabilityPrompt(id,selected,version);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
  async function execute(){setRunning(true);setRun(null);try{const baseline={org_id:id,complaint,prompt_key:selected||'classifier_system',model}; const current=await api.runObservabilityPlayground(baseline); const alternative=override.trim()?await api.runObservabilityPlayground({...baseline,prompt_override:override}):null; setRun({current,alternative})}catch(e){setError(e.message)}finally{setRunning(false)}}
  if(error) return <main style={{padding:40,color:'#f87171',background:'#0d0f1a',minHeight:'100vh'}}>Internal dashboard: {error}</main>
  if(!data) return <main style={{padding:40,color:'#94a3b8',background:'#0d0f1a',minHeight:'100vh'}}>Loading organisation intelligence…</main>
  const active=data.prompts?.find(p=>p.prompt_key===selected)
  return <main style={{minHeight:'100vh',background:'#0d0f1a',color:'#e2e8f0',padding:'32px clamp(18px,4vw,56px)',fontFamily:'system-ui,sans-serif'}}><Link href="/internal/intelligence" style={{color:'#60a5fa',fontSize:12,textDecoration:'none'}}>← all organisations</Link><div style={{margin:'16px 0 24px'}}><div style={{...mono,color:'#60a5fa',fontSize:10}}>ORGANISATION INTELLIGENCE</div><h1 style={{margin:'6px 0',fontSize:26}}>{data.organization.name}</h1><div style={{color:'#64748b',fontSize:12}}>{data.organization.slug} · {data.organization.active_sources?.join(' · ')||'No active sources'}</div></div>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:18}}>{[['events',data.metrics.total_events],['surfaced',data.metrics.surfaced],['suppressed',data.metrics.suppressed],['avg relevance',data.metrics.avg_relevance??'—'],['avg escalation',data.metrics.avg_escalation??'—'],['last event',data.metrics.last_event_at?new Date(data.metrics.last_event_at).toLocaleDateString():'—']].map(([l,v])=><div key={l} style={card}><div style={{...mono,fontSize:9,color:'#64748b'}}>{l}</div><div style={{fontSize:18,marginTop:4}}>{v}</div></div>)}</section>
    <section style={{...card,marginBottom:18}}><div style={{...mono,fontSize:10,color:'#94a3b8',marginBottom:10}}>AGENT PIPELINE</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{data.agents.map(a=><div key={`${a.name}-${a.model}`} style={{border:'1px solid #243047',borderRadius:7,padding:'8px 10px',minWidth:160}}><div style={{fontSize:12}}>{a.name}</div><div style={{fontSize:10,color:'#64748b',marginTop:4}}>{a.model} · prompt v{a.prompt_version??0}</div><div style={{fontSize:10,color:'#64748b'}}>{a.successful}/{a.executions} successful · last {a.last_execution?new Date(a.last_execution).toLocaleString():'—'}</div></div>)}</div></section>
    <section style={{display:'grid',gridTemplateColumns:'minmax(190px,260px) minmax(0,1fr)',gap:16,alignItems:'start'}}><div style={card}><div style={{...mono,fontSize:10,color:'#94a3b8',marginBottom:8}}>PROMPTS</div>{data.prompts.map(p=><button key={p.prompt_key} onClick={()=>choose(p)} style={{width:'100%',textAlign:'left',padding:'9px',marginBottom:5,border:'1px solid #243047',borderRadius:6,background:selected===p.prompt_key?'#191d2b':'transparent',color:'#e2e8f0',cursor:'pointer'}}><div style={{fontSize:12}}>{p.name}</div><div style={{fontSize:10,color:'#64748b'}}>v{p.version} · {p.is_default?'global default':'org override'}</div></button>)}</div><div style={{display:'grid',gap:16}}><div style={card}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{...mono,fontSize:10,color:'#94a3b8'}}>PROMPT MANAGEMENT</div><div style={{fontSize:14,marginTop:3}}>{active?.name}</div></div><span style={{fontSize:11,color:active?.is_default?'#fbbf24':'#4ade80'}}>{active?.is_default?'global default':'organisation override'}</span></div><textarea value={content} onChange={e=>setContent(e.target.value)} rows={13} style={{marginTop:12,width:'100%',boxSizing:'border-box',background:'#0d0f1a',color:'#d1d5db',border:'1px solid #243047',borderRadius:7,padding:10,fontSize:12,fontFamily:'ui-monospace,monospace'}}/><input value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Change summary for version history" style={{marginTop:8,width:'100%',boxSizing:'border-box',background:'#0d0f1a',color:'#e2e8f0',border:'1px solid #243047',borderRadius:6,padding:8,fontSize:12}}/><button onClick={save} disabled={saving||!selected} style={{marginTop:8,padding:'8px 12px',background:'#2563eb',color:'white',border:0,borderRadius:6,cursor:'pointer'}}>{saving?'saving…':'save new version'}</button><div style={{marginTop:14,...mono,fontSize:10,color:'#64748b'}}>VERSION HISTORY</div>{(data.versions?.[selected]||[]).map(v=><div key={v.id} style={{borderTop:'1px solid #1e2535',padding:'8px 0',fontSize:11}}>v{v.version} · {v.author_email||'Spill internal'} · {new Date(v.created_at).toLocaleString()}<br/><span style={{color:'#64748b'}}>{v.change_summary||'No summary'}</span><button disabled={saving||v.version===active?.version} onClick={()=>rollback(v.version)} style={{marginLeft:8,padding:'3px 6px',border:'1px solid #475569',borderRadius:4,background:'transparent',color:'#93c5fd',cursor:'pointer',fontSize:10}}>{v.version===active?.version?'current':'restore this version'}</button></div>)}</div>
      <div style={card}><div style={{...mono,fontSize:10,color:'#94a3b8'}}>AGENT PLAYGROUND</div><p style={{fontSize:12,color:'#64748b'}}>Runs the current prompt first, then an optional alternative using the chosen model. Playground changes are never saved automatically.</p><textarea value={complaint} onChange={e=>setComplaint(e.target.value)} rows={4} placeholder="Example customer complaint" style={{width:'100%',boxSizing:'border-box',background:'#0d0f1a',color:'#e2e8f0',border:'1px solid #243047',borderRadius:6,padding:8}}/><textarea value={override} onChange={e=>setOverride(e.target.value)} rows={4} placeholder="Optional alternative prompt" style={{width:'100%',boxSizing:'border-box',marginTop:8,background:'#0d0f1a',color:'#e2e8f0',border:'1px solid #243047',borderRadius:6,padding:8}}/><select value={model} onChange={e=>setModel(e.target.value)} style={{marginTop:8,background:'#0d0f1a',color:'#e2e8f0',border:'1px solid #243047',borderRadius:6,padding:8}}><option>gpt-4o-mini</option><option>gpt-4o</option></select><button disabled={running||!complaint.trim()} onClick={execute} style={{marginLeft:8,padding:'8px 12px',background:'#2563eb',color:'white',border:0,borderRadius:6,cursor:'pointer'}}>{running?'running…':'run comparison'}</button>{run&&<div style={{display:'grid',gridTemplateColumns:run.alternative?'1fr 1fr':'1fr',gap:8,marginTop:12}}><RunResult title="Current" result={run.current}/>{run.alternative&&<RunResult title="Alternative" result={run.alternative}/>}</div>}</div></div></section></main>
}
function RunResult({title,result}){return <div style={{background:'#0d0f1a',padding:10,borderRadius:6}}><div style={{...mono,color:'#60a5fa',fontSize:10,marginBottom:6}}>{title.toUpperCase()} · {result.model} · {result.latency_ms}ms</div><div style={{fontSize:11,color:'#94a3b8',marginBottom:6}}>relevance {result.metrics?.relevance ?? '—'} · escalation {result.metrics?.escalation_score ?? '—'} · accuracy {result.metrics?.classification_accuracy ?? 'needs label'} · hallucinations {result.metrics?.hallucinations ?? 'needs review'}</div><pre style={{margin:0,whiteSpace:'pre-wrap',fontSize:10,color:'#cbd5e1'}}>{JSON.stringify(result.output,null,2)}</pre></div>}
