'use client'
import { useEffect, useState } from 'react'
import { api } from '@/lib/api'
import { timeAgo } from '@/lib/auth'

const card = { background: '#12151e', border: '1px solid #1e2535', borderRadius: 10, padding: 16 }
const mono = { fontFamily: 'var(--font-mono), ui-monospace, monospace' }

export default function IntelligenceConsole() {
  const [orgs, setOrgs] = useState([]); const [traces, setTraces] = useState([]); const [selected, setSelected] = useState(null); const [detail, setDetail] = useState(null); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.getObservabilityOverview(), api.getObservabilityTraces()]).then(([a,b]) => { setOrgs(a.organizations || []); setTraces(b.traces || []) }).catch(e => setError(e.message)); }, []);
  async function openTrace(id) { try { const d = await api.getObservabilityTraces({ trace_id: id }); setSelected(id); setDetail(d); } catch (e) { setError(e.message) } }
  if (error) return <main style={{ minHeight: '100vh', background: '#0d0f1a', color: '#f87171', padding: 48, fontFamily: 'system-ui' }}>Operator console unavailable: {error}</main>
  return <main style={{ minHeight: '100vh', background: '#0d0f1a', color: '#e2e8f0', padding: '34px clamp(18px,4vw,56px)', fontFamily: 'system-ui, sans-serif' }}>
    <div style={{ marginBottom: 28 }}><div style={{ ...mono, color: '#60a5fa', fontSize: 11, letterSpacing: '.16em' }}>SPILL / INTERNAL ONLY</div><h1 style={{ fontSize: 25, fontWeight: 550, margin: '8px 0' }}>Organisation Intelligence</h1><p style={{ margin: 0, color: '#64748b', fontSize: 13 }}>Every surfaced decision is inspectable: source → agent → prompt version → quality gate → outcome.</p></div>
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(235px,1fr))', gap: 12, marginBottom: 24 }}>{orgs.map(o => <div key={o.id} style={card}><div style={{ display:'flex', justifyContent:'space-between', gap:10 }}><strong>{o.name}</strong><span style={{ ...mono, fontSize:10, color:'#64748b' }}>{o.slug}</span></div><div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:9, marginTop:15, fontSize:12 }}><Metric label="surfaced" value={o.surfaced}/><Metric label="suppressed" value={o.suppressed}/><Metric label="avg quality" value={o.avg_quality ?? '—'}/><Metric label="false positive" value={o.false_positive_rate == null ? '—' : `${o.false_positive_rate}%`}/></div><div style={{ marginTop:12, fontSize:11, color:'#64748b' }}>{(o.top_categories || []).slice(0,3).join(' · ') || 'No classified categories yet'}</div></div>)}</section>
    <section style={{ display:'grid', gridTemplateColumns:'minmax(330px,1fr) minmax(360px,1.1fr)', gap:16, alignItems:'start' }}>
      <div style={card}><div style={{ ...mono, color:'#94a3b8', fontSize:11, letterSpacing:'.1em', marginBottom:12 }}>EVENT TRACE EXPLORER</div>{traces.length ? traces.map(t => <button key={t.id} onClick={() => openTrace(t.id)} style={{ width:'100%', textAlign:'left', background:selected===t.id?'#191d2b':'transparent', border:'none', borderTop:'1px solid #1e2535', color:'inherit', padding:'12px 4px', cursor:'pointer' }}><div style={{ display:'flex', justifyContent:'space-between', gap:10, fontSize:12 }}><span style={{ color: t.decision==='surfaced' ? '#4ade80' : '#fbbf24' }}>{t.decision}</span><span style={{ color:'#475569' }}>{timeAgo(t.created_at)}</span></div><div style={{ margin:'5px 0', fontSize:13 }}>{t.title || 'Suppressed candidate'}</div><div style={{ ...mono, fontSize:10, color:'#64748b' }}>{t.org_name} · {t.source} · query: {t.metadata?.detected_query || 'source match'} · quality {t.quality?.score ?? '—'} · escalation {t.escalation_score ?? '—'}</div></button>) : <p style={{ color:'#64748b', fontSize:13 }}>No traces yet. Run a refresh to begin recording decisions.</p>}</div>
      <div style={card}>{detail ? <TraceDetail detail={detail}/> : <div style={{ color:'#64748b', fontSize:13, padding:20 }}>Select an event to inspect its original content, agent outputs, prompt versions, model usage, and quality decision.</div>}</div>
    </section>
  </main>
}
function Metric({ label, value }) { return <div><div style={{ ...mono, fontSize:9, color:'#475569', textTransform:'uppercase' }}>{label}</div><div style={{ fontSize:16, marginTop:2 }}>{value ?? 0}</div></div> }
function TraceDetail({ detail }) { const t=detail.trace; return <><div style={{ display:'flex', justifyContent:'space-between', gap:12 }}><div><div style={{ ...mono, color:'#60a5fa', fontSize:10 }}>TRACE {t.id.slice(0,8)}</div><h2 style={{ fontSize:16, margin:'6px 0' }}>{t.title || t.metadata?.title || 'Candidate signal'}</h2></div><span style={{ color:t.decision==='surfaced'?'#4ade80':'#fbbf24', fontSize:12 }}>{t.decision}</span></div><pre style={{ whiteSpace:'pre-wrap', maxHeight:150, overflow:'auto', color:'#94a3b8', background:'#0d0f1a', padding:10, borderRadius:6, fontSize:11 }}>{t.body || 'Source retained in the source-processing observation.'}</pre><div style={{ margin:'14px 0 8px', ...mono, color:'#64748b', fontSize:10 }}>QUALITY · {t.quality?.score}/100 — relevance {t.quality?.relevance}, impact {t.quality?.impact}, confidence {t.quality?.confidence}, novelty {t.quality?.novelty}</div>{detail.observations.map(o => <details key={o.id} style={{ borderTop:'1px solid #1e2535', padding:'10px 0' }} open={o.kind==='agent'}><summary style={{ cursor:'pointer', fontSize:13 }}>{o.name} <span style={{ ...mono, color:'#64748b', fontSize:10 }}> {o.model || o.kind} · {o.latency_ms || 0}ms · {o.input_tokens || 0}/{o.output_tokens || 0} tokens</span></summary><div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8, marginTop:9 }}><Json title="input / prompt" value={o.input}/><Json title="output" value={o.output}/></div>{o.error && <div style={{ color:'#f87171', fontSize:11 }}>{o.error}</div>}</details>)}</> }
function Json({ title, value }) { return <div><div style={{ ...mono, color:'#475569', fontSize:9, marginBottom:4 }}>{title}</div><pre style={{ margin:0, padding:8, overflow:'auto', maxHeight:180, whiteSpace:'pre-wrap', fontSize:10, background:'#0d0f1a', borderRadius:5, color:'#94a3b8' }}>{JSON.stringify(value, null, 2)}</pre></div> }
